model:
  d_fft: 1024
  d_model: 512
  dropout: 0.1
  heads: 4
  layers: 6
  type: transformer
paths:
  checkpoint_dir: checkpoints
  data_dir: datasets
preprocessing:
  char_repeats: 3
  languages:
  - de
  - en_us
  - bn
  lowercase: true
  n_val: 5000
  phoneme_symbols:
  - a
  - b
  - d
  - e
  - f
  - g
  - h
  - i
  - j
  - k
  - l
  - m
  - n
  - o
  - p
  - r
  - s
  - t
  - u
  - v
  - w
  - x
  - y
  - z
  - 'i:'
  - "\u026A"
  - "\u028A"
  - 'u:'
  - "\u026A\u0259"
  - "e\u026A"
  - "\u0259\u028A"
  - e
  - "\u0259"
  - "\u025C:"
  - "\u0254:"
  - "\u028A\u0259"
  - "\u0254\u026A"
  - "\xE6"
  - "\u028C"
  - "\u0251:"
  - "\u0252"
  - "e\u0259"
  - "a\u026A"
  - "a\u028A"
  - p
  - b
  - t
  - d
  - k
  - g
  - f
  - v
  - "\u03B8"
  - "\xF0"
  - s
  - z
  - "\u0283"
  - "\u0292"
  - h
  - m
  - n
  - "\u014B"
  - l
  - r
  - w
  - j
  - "\u02A7"
  - "\u02A4"
  text_symbols:
  - "\u0981"
  - "\u09BE"
  - "\u09BF"
  - "\u09C0"
  - "\u09C1"
  - "\u09C2"
  - "\u09C3"
  - "\u09C7"
  - "\u09C8"
  - "\u09CB"
  - "\u09CC"
  - "\u09CD"
  - "\u09CE"
  - "\u0983"
  - "\u0982"
  - "\u0985"
  - "\u0986"
  - "\u0987"
  - "\u0988"
  - "\u0989"
  - "\u098A"
  - "\u098B"
  - "\u098C"
  - "\u098F"
  - "\u0990"
  - "\u0993"
  - "\u0994"
  - "\u0995"
  - "\u0996"
  - "\u0997"
  - "\u0998"
  - "\u0999"
  - "\u099A"
  - "\u099B"
  - "\u099C"
  - "\u099D"
  - "\u099E"
  - "\u099F"
  - "\u09A0"
  - "\u09A1"
  - "\u09A2"
  - "\u09A3"
  - "\u09A4"
  - "\u09A5"
  - "\u09A6"
  - "\u09A7"
  - "\u09A8"
  - "\u09AA"
  - "\u09AB"
  - "\u09AC"
  - "\u09AD"
  - "\u09AE"
  - "\u09AF"
  - "\u09B0"
  - "\u09B2"
  - "\u09B6"
  - "\u09B7"
  - "\u09B8"
  - "\u09B9"
  - "\u09DC"
  - "\u09DD"
  - "\u09DF"
training:
  batch_size: 32
  batch_size_val: 32
  checkpoint_steps: 100000
  ddp_backend: nccl
  ddp_host: localhost
  ddp_post: '12355'
  epochs: 10
  generate_steps: 500
  learning_rate: 0.0001
  n_generate_samples: 10
  scheduler_plateau_factor: 0.5
  scheduler_plateau_patience: 10
  store_phoneme_dict_in_model: true
  validate_steps: 500
  warmup_steps: 100
