model:
  d_fft: 1024
  d_model: 512
  dropout: 0.1
  heads: 4
  layers: 6
  type: transformer
paths:
  checkpoint_dir: Model_Checkpoints/Deep_Phonemizer/Forward_Model_Checkpoints/
  data_dir: Model_Data/Deep_Phonemizer/Forward_Model_Data/
preprocessing:
  char_repeats: 2
  languages:
  - de
  - en_us
  - bn
  lowercase: false
  n_val: 5000
  phoneme_symbols:
  - o
  - "\u02B1"
  - "\u0254"
  - "\xF8"
  - g
  - "\u201D"
  - d
  - s
  - u
  - m
  - "\u02D0"
  - b
  - "\u2013"
  - z
  - f
  - "\u0361"
  - "\u027D"
  - "\u027E"
  - "\u032A"
  - v
  - t
  - r
  - "\u025B"
  - h
  - k
  - "\u032F"
  - l
  - "\u026A"
  - a
  - "\u201C"
  - "\u2014"
  - "\u0250"
  - "\u014B"
  - c
  - "\u0306"
  - "\u02B2"
  - "\u0303"
  - "\u02B7"
  - e
  - "\u0283"
  - "\u2018"
  - p
  - n
  - "\u025F"
  - "\u02B0"
  text_symbols:
  - "\u0981"
  - "\u09BE"
  - "\u09BF"
  - "\u09C0"
  - "\u09C1"
  - "\u09C2"
  - "\u09C3"
  - "\u09C7"
  - "\u09C8"
  - "\u09CB"
  - "\u09CC"
  - "\u09CD"
  - "\u09CE"
  - "\u0983"
  - "\u0982"
  - "\u0985"
  - "\u0986"
  - "\u0987"
  - "\u0988"
  - "\u0989"
  - "\u098A"
  - "\u098B"
  - "\u098C"
  - "\u098F"
  - "\u0990"
  - "\u0993"
  - "\u0994"
  - "\u0995"
  - "\u0996"
  - "\u0997"
  - "\u0998"
  - "\u0999"
  - "\u099A"
  - "\u099B"
  - "\u099C"
  - "\u099D"
  - "\u099E"
  - "\u099F"
  - "\u09A0"
  - "\u09A1"
  - "\u09A2"
  - "\u09A3"
  - "\u09A4"
  - "\u09A5"
  - "\u09A6"
  - "\u09A7"
  - "\u09A8"
  - "\u09AA"
  - "\u09AB"
  - "\u09AC"
  - "\u09AD"
  - "\u09AE"
  - "\u09AF"
  - "\u09B0"
  - "\u09B2"
  - "\u09B6"
  - "\u09B7"
  - "\u09B8"
  - "\u09B9"
  - "\u09DC"
  - "\u09DD"
  - "\u09DF"
training:
  batch_size: 32
  batch_size_val: 32
  checkpoint_steps: 100000
  ddp_backend: nccl
  ddp_host: localhost
  ddp_post: '12355'
  epochs: 10
  generate_steps: 500
  learning_rate: 0.0001
  n_generate_samples: 10
  scheduler_plateau_factor: 0.5
  scheduler_plateau_patience: 10
  store_phoneme_dict_in_model: true
  validate_steps: 500
  warmup_steps: 100
