model:
  d_fft: 1024
  d_model: 512
  dropout: 0.1
  heads: 4
  layers: 6
  type: transformer
paths:
  checkpoint_dir: Model_Checkpoints/Deep_Phonemizer/Forward_Model_Checkpoints/
  data_dir: Model_Data/Deep_Phonemizer/Forward_Model_Data/
preprocessing:
  char_repeats: 2
  languages:
  - de
  - en_us
  - bn
  lowercase: false
  n_val: 5000
  phoneme_symbols:
  - ':'
  - "\u0262"
  - "\u029D"
  - "\u0295"
  - "\u027B"
  - s
  - q
  - "\u0273"
  - "\u0276"
  - "\u0127"
  - "\u03B2"
  - "\u028A"
  - "\u027E"
  - "\u01C3"
  - "\u027A"
  - p
  - d
  - f
  - "\u0256"
  - "\u0288"
  - "\u0153"
  - "\u0260"
  - "\u028C"
  - r
  - ''''
  - "\u030D"
  - t
  - "\u014B"
  - "\xE6"
  - ;
  - "\u0268"
  - j
  - .
  - "\u025D"
  - "\u0275"
  - "\u0270"
  - "\u029C"
  - ','
  - "\u0252"
  - "\xF0"
  - "\u0290"
  - "\u0284"
  - "\u0329"
  - "\u0298"
  - "\u01C0"
  - "\u03B8"
  - "\u029B"
  - "\u025A"
  - k
  - "\u0257"
  - "\u02C8"
  - "\u029F"
  - "\u0255"
  - "\u2C71"
  - "\u02DE"
  - (
  - "\u026E"
  - "\u0272"
  - "\u0278"
  - "\u0281"
  - "\u0292"
  - "\xE7"
  - l
  - "\u0283"
  - "\u0264"
  - '?'
  - "\u028B"
  - "\u026F"
  - '!'
  - "\u0251"
  - v
  - "\u0253"
  - "\u02D1"
  - "\u025C"
  - "\u025E"
  - b
  - "\u026B"
  - "\u1D7B"
  - n
  - "\u0271"
  - a
  - "\u0294"
  - "\u025B"
  - "\u0325"
  - "\u02A1"
  - x
  - "\u028F"
  - "\u0279"
  - i
  - z
  - o
  - "\u026A"
  - "\u0291"
  - "\u02A2"
  - "\u0267"
  - "\xF8"
  - c
  - "\u03C7"
  - "\u026C"
  - m
  - "\u0250"
  - "\u0258"
  - "\u0274"
  - "\u0289"
  - "\u0259"
  - "\u025F"
  - "\u0282"
  - "\u01C2"
  - "\u0254"
  - "\u01C1"
  - "\u0299"
  - "\u027D"
  - "\u02D0"
  - "\u026D"
  - w
  - "\u0266"
  - "\u0280"
  - g
  - "\u0261"
  - "\u028D"
  - "\u02CC"
  - _
  - ' '
  - "\u0265"
  - u
  - )
  - "\u032F"
  - e
  - y
  - "\u0361"
  - '-'
  - "\u028E"
  - h
  - "\u0263"
  - "\u0303"
  text_symbols:
  - "\u0981"
  - "\u09BE"
  - "\u09BF"
  - "\u09C0"
  - "\u09C1"
  - "\u09C2"
  - "\u09C3"
  - "\u09C7"
  - "\u09C8"
  - "\u09CB"
  - "\u09CC"
  - "\u09CD"
  - "\u09CE"
  - "\u0983"
  - "\u0982"
  - "\u0985"
  - "\u0986"
  - "\u0987"
  - "\u0988"
  - "\u0989"
  - "\u098A"
  - "\u098B"
  - "\u098C"
  - "\u098F"
  - "\u0990"
  - "\u0993"
  - "\u0994"
  - "\u0995"
  - "\u0996"
  - "\u0997"
  - "\u0998"
  - "\u0999"
  - "\u099A"
  - "\u099B"
  - "\u099C"
  - "\u099D"
  - "\u099E"
  - "\u099F"
  - "\u09A0"
  - "\u09A1"
  - "\u09A2"
  - "\u09A3"
  - "\u09A4"
  - "\u09A5"
  - "\u09A6"
  - "\u09A7"
  - "\u09A8"
  - "\u09AA"
  - "\u09AB"
  - "\u09AC"
  - "\u09AD"
  - "\u09AE"
  - "\u09AF"
  - "\u09B0"
  - "\u09B2"
  - "\u09B6"
  - "\u09B7"
  - "\u09B8"
  - "\u09B9"
  - "\u09DC"
  - "\u09DD"
  - "\u09DF"
training:
  batch_size: 32
  batch_size_val: 32
  checkpoint_steps: 100000
  ddp_backend: nccl
  ddp_host: localhost
  ddp_post: '12355'
  epochs: 10
  generate_steps: 500
  learning_rate: 0.0001
  n_generate_samples: 10
  scheduler_plateau_factor: 0.5
  scheduler_plateau_patience: 10
  store_phoneme_dict_in_model: true
  validate_steps: 500
  warmup_steps: 100
